# labels auto assigned to PR, keep in sync with labels.yml
# Type
documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["README.md", "*.md", "docs/**"]
dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["**/uv.lock", "package-lock.json"]
      - head-branch: ["^dependabot"]
configurations:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/tool-configurations/*"]
# Language
markdown:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              [
                "docs/*.md",
                "*.md",
                "LICENCE",
                ".github/pull_request_template.md",
              ]
javascript:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              ["*.js", "**/*.js"]
just:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["Justfile", "**/*.just"]
# Components
git_hooks:
  - any:
      - changed-files:
          - any-glob-to-any-file: ["lefthook.yml"]
github_actions:
  - any:
      - changed-files:
          - any-glob-to-any-file: [".github/workflows/*", ".github/actions/*"]
