name: "Code Checks"

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read
  packages: read

env:
  FORCE_COLOR: 1

jobs:
  common-code-checks:
    name: Common Code Checks
    permissions:
      contents: read
      actions: read
      pull-requests: write
      security-events: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-code-checks.yml@e30aab8ee9515b2bf9326a17e1476d4025dcd554 # v2025.07.28.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}

  codeql-checks:
    name: CodeQL Analysis
    permissions:
      contents: read
      security-events: write
    strategy:
      matrix:
        language: [actions, javascript]
    uses: JackPlowman/reusable-workflows/.github/workflows/codeql-analysis.yml@e30aab8ee9515b2bf9326a17e1476d4025dcd554 # v2025.07.28.01
    with:
      language: ${{ matrix.language }}
