name: "Sync labels"

on:
  push:
    branches:
      - main
    paths:
      - .github/tool-configurations/labels.yml
  workflow_dispatch:

permissions: {}

jobs:
  configure-labels:
    name: Configure Labels
    permissions:
      contents: read
      pull-requests: write
    uses: JackPlowman/reusable-workflows/.github/workflows/common-sync-labels.yml@887ec8c4b1a314438ac01be52bb850f8b6fc73d0 # v2025.08.25.01
    secrets:
      workflow_github_token: ${{ secrets.GITHUB_TOKEN }}
